services:
  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=SAPE.settings.prod
    command: gunicorn SAPE.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./static:/app/static
      - media_volume:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    expose:
      - "8000"

  news_scheduler:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=SAPE.settings.prod
    command: >
      sh -c "while true; do
        python manage.py atualizar_noticias;
        sleep 3600;
      done"
    volumes:
      - media_volume:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    depends_on:
      - web
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web
    restart: always

volumes:
  media_volume:
