services:
  web:
    build: .
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=SAPE.settings.prod
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: gunicorn SAPE.wsgi:application --bind 0.0.0.0:8000 --workers 1 --threads 4 --timeout 300
    volumes:
      - ./static:/app/static
      - media_volume:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    expose:
      - "8000"
    restart: always

  redis:
    image: redis:7-alpine
    restart: always

  celery_worker:
    build: .
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=SAPE.settings.prod
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    # SQLite => mantenha concorrÃªncia 1 para evitar lock
    command: celery -A SAPE worker -l info --concurrency=1
    volumes:
      - media_volume:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    depends_on:
      - redis
    restart: always

  celery_beat:
    build: .
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=SAPE.settings.prod
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A SAPE beat -l info
    depends_on:
      - redis
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web
    restart: always

volumes:
  media_volume:
